name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: xcode
        run: |
          sudo xcode-select -s '/Applications/Xcode_11.6.app/Contents/Developer'
          xcodebuild -version

      - name: ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: build
        run: rake build
