name: Build

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: xcode
        run: |
          sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
          xcodebuild -version

      - name: ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: build
        run: rake build
