name: Build

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: xcode
        run: |
          sudo xcode-select -s '/Applications/Xcode_13.4.1.app/Contents/Developer'
          xcodebuild -version

      - name: rustc
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            override: true

      - name: ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: build
        run: rake build
