name: Build WASM

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: version
        run: emcc -v
