name: Subtree Push

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [master]

jobs:
  subtree-push:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' # a fork must not run this

    steps:
      - name: ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.PAT }}

      - name: subtree push
        run: rake all subtree:push
