name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os:   [macos-latest, windows-latest, ubuntu-latest]
        ruby: ['3.1', '3.2', '3.3']
      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:
      - name: ruby ${{matrix.ruby}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}

      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        if: runner.os == 'linux'
        run: sudo apt-get install -y libopenal-dev libglew-dev libsdl2-dev

      - name: packages
        run: rake packages

      - name: lib
        run: rake lib

      - name: ext
        run: rake ext

      - name: test
        if: runner.os == 'macos'
        run: rake test

      - name: test
        if: runner.os == 'windows'
        run: rake xot rucy rays reflex test
