name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os:   [macos-latest, windows-latest]
        ruby: ['3.0', '3.1', '3.2', '3.3']
      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:
      - name: ruby ${{matrix.ruby}}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}

      - name: checkout
        uses: actions/checkout@v4

      - name: packages
        run: rake packages

      - name: lib
        run: rake lib

      - name: ext
        run: rake ext

      - name: test
        run: rake test
